services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: "local_password"
    ports:
<<<<<<< HEAD:infra/compose.yaml
      - "5432:5432"
=======
      - "5432:5432"
>>>>>>> afd8bb9 (changes on):compose.yaml
